# Nginx and CV access
#
# Access via "http://localhost:80"
#
# Create OD container
object_detection:
  image: object_detection_image
  container_name: object_detection
  restart: always
  environment:
    - TERM=xterm
  hostname: '127.0.0.1'
  ports:
    - "80:80"             #http
    - "443:443"           #https
  volumes:
    #Volume moutning for image entry
    - /Users/chamalgomes/Documents/MLSA/object_detection/Version_1/snaps/js_face_recognition.html:/usr/share/nginx/html/index.html
    - /Users/chamalgomes/Documents/MLSA/object_detection/Version_1/snaps/opencv.js:/usr/share/nginx/html/opencv.js
    - /Users/chamalgomes/Documents/MLSA/object_detection/Version_1/snaps/utils.js:/usr/share/nginx/html/utils.js
