#!/bin/bash

sudo apt -y update
sudo apt -y upgrade
sudo apt -y full-upgrade
sudo apt -y install autoconf automake build-essential pkgconf libtool git libzip-dev libjpeg-dev gettext libmicrohttpd-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libavdevice-dev default-libmysqlclient-dev libpq-dev libsqlite3-dev libwebp-dev

if dpkg -s motion &>/dev/null; then
  echo 'motion is installed'
else
  wget https://github.com/Motion-Project/motion/releases/download/release-4.7.1/trixie_motion_4.7.1-1_armhf.deb
  sudo dpkg -i trixie_motion_4.7.1-1_armhf.deb
sudo tee -a /etc/motion/motion.conf > /dev/null <<EOT
# Rename this distribution example file to motion.conf
#
# This config file was generated by motion 4.2.2
# Documentation:  /usr/share/doc/motion/motion_guide.html
#
# This file contains only the basic configuration options to get a
# system working.  There are many more options available.  Please
# consult the documentation for the complete list of all options.
#

############################################################
# System control configuration parameters
############################################################

# Start in daemon (background) mode and release terminal.
daemon on

# Start in Setup-Mode, daemon disabled.
setup_mode off

# File to store the process ID.
; pid_file value

# File to write logs messages into.  If not defined stderr and syslog is used.
; log_file value

# Level of log messages [1..9] (EMG, ALR, CRT, ERR, WRN, NTC, INF, DBG, ALL).
log_level 6

# Target directory for pictures, snapshots and movies
target_dir /motion

# Video device (e.g. /dev/video0) to be used for capturing.
videodevice /dev/video0

# Parameters to control video device.  See motion_guide.html
; vid_control_params value

# The full URL of the network camera stream.
; netcam_url value

# Name of mmal camera (e.g. vc.ril.camera for pi camera).
; mmalcam_name value

# Camera control parameters (see raspivid/raspistill tool documentation)
; mmalcam_control_params value

############################################################
# Image Processing configuration parameters
############################################################

# Image width in pixels.
width 320

# Image height in pixels.
height 240

# Maximum number of frames to be captured per second.
framerate 10

stream_maxrate 10

# Text to be overlayed in the lower left corner of images
text_left

# Text to be overlayed in the lower right corner of images.
text_right

############################################################
# Motion detection configuration parameters
############################################################

# Always save pictures and movies even if there was no motion.
emulate_motion off

# Threshold for number of changed pixels that triggers motion.
threshold 1500

# Noise threshold for the motion detection.
noise_level 32

# Despeckle the image using (E/e)rode or (D/d)ilate or (l)abel.
despeckle_filter EedDl

# Number of images that must contain motion to trigger an event.
minimum_motion_frames 1

# Gap in seconds of no motion detected that triggers the end of an event.
event_gap 4

# The number of pre-captured (buffered) pictures from before motion.
pre_capture 3

# Number of frames to capture after motion is no longer detected.
post_capture 0

############################################################
# Script execution configuration parameters
############################################################

# Command to be executed when an event starts.
on_event_start /usr/bin/curl http://localhost:8080/motion/START

# Command to be executed when an event ends.
on_event_end /usr/bin/curl http://localhost:8080/motion/END

# Command to be executed when a movie file is closed.
; on_movie_end value

############################################################
# Picture output configuration parameters
############################################################

# Output pictures when motion is detected
picture_output off

# File name(without extension) for pictures relative to target directory
picture_filename %Y%m%d%H%M%S-%q

############################################################
# Movie output configuration parameters
############################################################

# Create movies of motion events.
movie_output off

# Maximum length of movie in seconds.
movie_max_time 60

# The encoding quality of the movie. (0=use bitrate. 1=worst quality, 100=best)
movie_quality 45

# Container/Codec to used for the movie. See motion_guide.html
movie_codec mkv

# File name(without extension) for movies relative to target directory
movie_filename %t-%v-%Y%m%d%H%M%S

############################################################
# Webcontrol configuration parameters
############################################################

# Port number used for the webcontrol.
webcontrol_port 8020

# Restrict webcontrol connections to the localhost.
webcontrol_localhost on

# Type of configuration options to allow via the webcontrol.
webcontrol_parms 0

############################################################
# Live stream configuration parameters
############################################################

# The port number for the live stream.
stream_port 8021

# Restrict stream connections to the localhost.
stream_localhost off

##############################################################
# Camera config files - One for each camera.
##############################################################
; camera /etc/motion/camera1.conf
; camera /etc/motion/camera2.conf
; camera /etc/motion/camera3.conf
; camera /etc/motion/camera4.conf

##############################################################
# Directory to read '.conf' files for cameras.
##############################################################
; camera_dir /etc/motion/conf.d
EOT

sudo tee -a /etc/default/motion > /dev/null <<EOT
start_motion_daemon=yes
EOT

  sudo systemctl enable motion
  sudo systemctl start motion
fi

if ! command -v nvm >/dev/null 2>&1
then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

  nvm install 12
  nvm alias default 12
fi

if [[ "$(npm list -g electron)" =~ "empty" ]]; then
    echo "Installing electron ..."
    npm install -g --arch=armv7l electron@6.1.7 --unsafe-perm=true --allow-root
else
    echo "electron is already installed"
fi

sudo mkdir -p /var/smartmirror/
sudo chmod 777 -R /var/smartmirror/
mkdir -p /var/smartmirror/logs/

sudo tee -a /var/smartmirror/run.sh > /dev/null <<EOT
#!/bin/bash
export DISPLAY=:0.0
export LOG_DIRECTORY=/var/smartmirror/logs/

#/var/smartmirror/Alexa/AlexaApp /var/smartmirror/Alexa/AlexaClientSDKConfig.json /var/smartmirror/Alexa/resources DEBUG9

java -jar /var/smartmirror/smartmirror-backend-web-1.0.jar &

sleep 20
/var/smartmirror/smartmirror-ui/smartmirror-ui-app
EOT

sudo tee -a /etc/systemd/system/smartmirror.service > /dev/null <<EOT
[Unit]
Description=Smartmirror
After=syslog.target

[Service]
User=pi
WorkingDirectory=/var/smartmirror
ExecStart=/var/smartmirror/run.sh


[Install]
WantedBy=multi-user.target
EOT

sudo chmod +x /var/smartmirror/smartmirror-ui/smartmirror-ui-app
sudo chmod +x /var/smartmirror/smartmirror-backend-web-1.0.jar
sudo chmod +x /var/smartmirror/run.sh

sudo systemctl enable smartmirror.service
sudo systemctl start smartmirror.service

export DISPLAY=:0
xset -dpms
xset s noblank
xset s off
xdg-screensaver status